# Créer un pipeline GitHub Actions qui fait un echo "Hello pipelines' world !.
name: Lab03 Pipeline

on:
    push:
        branches:
            - lab03
    pull_request:
        branches:
            - main
            - lab03
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Run Lab 2 Script
              run: bash ./deliverables/lab02/lab2.sh
