# Créer un pipeline GitHub Actions qui fait un echo "Hello pipelines' world !.
name: Lab03 Pipeline

on:
    push:
        branches:
            - lab03
    pull_request:
        branches:
            - main
            - lab03
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Greet the world
              run: echo "Hello pipelines' world !"

            - name: Display Runner Info
              run: |
                  echo "Running on $(uname -a)"
                  echo "Workflow name: ${{ github.workflow }}"
                  echo "Event name: ${{ github.event_name }}"
                  echo "Repository: ${{ github.repository }}"
